<?php
$collection = Mage::getModel('catalog/product')->getCollection()
    ->addAttributeToFilter('status', 1) // enabled
    ->addUrlRewrite()
    ->addPriceData()
    ->addStoreFilter($store_id)
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('top_product',array('eq'=>1));
$_helper = $this->helper('catalog/output');
?>
<?php if (!$collection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php $_collectionSize = $collection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <ul class="products-grid" data-equalizer="pgrid">
                <?php $i = 0;
                foreach ($collection as $_product): ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"
                        data-equalizer-watch="pgrid">
                        <div class="panel">
                            <?php if ($_product->getAttributeText('manufacturer')): ?>
                                <?php $brand = $_product->getAttributeText('manufacturer') ?>
                                <div class="product-brand">
                                    <img src="/media/catalog/brands/<?php echo clean($brand) ?>.png"
                                         alt="<?php echo $brand ?> Logo">
                                </div>
                            <?php endif; ?>
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                        title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h2>
                            <div class="row">
                                <div class="small-10 small-centered columns products-image">
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                       class="product-image small-centered">
                                        <img
                                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"
                                            width="135" height="135"
                                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                    </a>
                                </div>
                            </div>
                            <?php if ($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <div class="actions floor">
                                <ul class="button-group stack-for-small">
                                    <li><a href="<?php echo $_product->getProductUrl() ?>" class="button"><?php echo $this->__('Details') ?></a></li>
                                    <?php if ($_product->isSaleable()): ?>
                                        <li><a href="<?php echo $this->getAddToCartUrl($_product) ?>" class="button" title="<?php echo $this->__('Add to Cart') ?>"><?php echo $this->__('Add to Cart') ?></a></li>
                                    <?php else: ?>
                                        <p class="availability out-of-stock">
                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
