<?php
if (!function_exists('clean_related')) {
    function clean_related($string)
    {

        $string = str_replace(' ', '-', $string); // Replaces all spaces with hyphens.
//$string = preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
        $string = strtolower($string);
        $utf8 = array(
            '/[áàâãªä]/u' => 'a',
            '/[ÁÀÂÃÄ]/u' => 'A',
            '/[ÍÌÎÏ]/u' => 'I',
            '/[íìîï]/u' => 'i',
            '/[éèêë]/u' => 'e',
            '/[ÉÈÊË]/u' => 'E',
            '/[óòôõºö]/u' => 'o',
            '/[ÓÒÔÕÖ]/u' => 'O',
            '/[úùûü]/u' => 'u',
            '/[ÚÙÛÜ]/u' => 'U',
            '/ç/' => 'c',
            '/Ç/' => 'C',
            '/ñ/' => 'n',
            '/Ñ/' => 'N',
            '/–/' => '-', // UTF-8 hyphen to "normal" hyphen
            '/[’‘‹›‚]/u' => ' ', // Literally a single quote
            '/[“”«»„]/u' => ' ', // Double quote
            '/ /' => ' ', // nonbreaking space (equiv. to 0x160)
        );

        return preg_replace(array_keys($utf8), array_values($utf8), $string); // Replaces multiple hyphens with single one.
    }
}
?>
<?php if ($this->getItems()->getSize()): ?>
    <p><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#"
                                                                            onclick="selectAllRelated(this);return false;"><?php echo $this->__('select all') ?></a>
    </p>
    <ul class="products-grid">
        <?php foreach ($this->getItems() as $_item): ?>
            <li class="item<?php if ($_item->isComposite() || !$_item->isSaleable()): ?>  super-products<?php endif; ?>">
                    <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                        <span class="checkbox-container">
                <?php if (!$_item->getRequiredOptions()): ?>
                    <input type="checkbox" class="related-checkbox left"
                           id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]"
                           value="<?php echo $_item->getId() ?>"/>
                <?php endif; ?>
                </span>
                    <?php else: ?>
                        <span class="checkbox-container">&nbsp;</span>
                    <?php endif; ?>
                    <?php if ($_item->getAttributeText('manufacturer')): ?>
                        <?php $brand = $_item->getAttributeText('manufacturer') ?>
                        <div class="product-brand">
                            <img src="/media/catalog/brands/<?php echo clean_related($brand) ?>.png"
                                 alt="<?php echo $brand ?> Logo" width="100" height="38">
                        </div>
                    <?php endif; ?>
                    <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <div class="product-images float-center">
                        <a href="<?php echo $_item->getProductUrl() ?>" class="product-image small-centered"><img
                                src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100) ?>"
                                alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="100" height="100"/></a>
                    </div>
                    <div class="product-details">
                        <?php echo $this->getLayout()->createBlock('catalog/product_price')
                            ->setTemplate('catalog/product/price_catalog.phtml')
                            ->setProduct($_item)
                            ->setDisplayMinimalPrice(true)
                            ->setIdSuffix($idSuffix='amit')
                            ->toHtml(); ?>
                        <?php //echo $this->getPriceHtml($_item, true) ?>
                    </div>
            </li>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">
        <!--
        $$('.related-checkbox').each(function (elem) {
            Event.observe(elem, 'click', addRelatedToProduct)
        });

        var relatedProductsCheckFlag = false;
        function selectAllRelated(txt) {
            if (relatedProductsCheckFlag == false) {
                $$('.related-checkbox').each(function (elem) {
                    elem.checked = true;
                });
                relatedProductsCheckFlag = true;
                txt.innerHTML = "<?php echo $this->__('unselect all') ?>";
            } else {
                $$('.related-checkbox').each(function (elem) {
                    elem.checked = false;
                });
                relatedProductsCheckFlag = false;
                txt.innerHTML = "<?php echo $this->__('select all') ?>";
            }
            addRelatedToProduct();
        }

        function addRelatedToProduct() {
            var checkboxes = $$('.related-checkbox');
            var values = [];
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i].checked) values.push(checkboxes[i].value);
            }
            if ($('related-products-field')) {
                $('related-products-field').value = values.join(',');
            }
        }
        //-->
    </script>
<?php endif ?>